/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root"
import { Route as UsageRouteImport } from "./routes/usage"
import { Route as SignupRouteImport } from "./routes/signup"
import { Route as SettingsRouteImport } from "./routes/settings"
import { Route as LoginRouteImport } from "./routes/login"
import { Route as CreateRouteImport } from "./routes/create"
import { Route as AdminRouteImport } from "./routes/admin"
import { Route as IndexRouteImport } from "./routes/index"
import { Route as AdminUsersRouteImport } from "./routes/admin/users"
import { Route as AdminJobsRouteImport } from "./routes/admin/jobs"
import { Route as AdminInvitesRouteImport } from "./routes/admin/invites"
import { Route as AdminArchiveRouteImport } from "./routes/admin/archive"
import { Route as ProblemProblem_idIndexRouteImport } from "./routes/problem/$problem_id/index"
import { Route as ProblemProblem_idResearchRouteImport } from "./routes/problem/$problem_id/research"
import { Route as ProblemProblem_idFilesRouteImport } from "./routes/problem/$problem_id/files"
import { Route as ProblemProblem_idConversationsRouteImport } from "./routes/problem/$problem_id/conversations"
import { Route as AdminJobQueue_nameJob_idRouteImport } from "./routes/admin/job/$queue_name.$job_id"

const UsageRoute = UsageRouteImport.update({
  id: "/usage",
  path: "/usage",
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: "/signup",
  path: "/signup",
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: "/settings",
  path: "/settings",
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: "/login",
  path: "/login",
  getParentRoute: () => rootRouteImport,
} as any)
const CreateRoute = CreateRouteImport.update({
  id: "/create",
  path: "/create",
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: "/admin",
  path: "/admin",
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: "/users",
  path: "/users",
  getParentRoute: () => AdminRoute,
} as any)
const AdminJobsRoute = AdminJobsRouteImport.update({
  id: "/jobs",
  path: "/jobs",
  getParentRoute: () => AdminRoute,
} as any)
const AdminInvitesRoute = AdminInvitesRouteImport.update({
  id: "/invites",
  path: "/invites",
  getParentRoute: () => AdminRoute,
} as any)
const AdminArchiveRoute = AdminArchiveRouteImport.update({
  id: "/archive",
  path: "/archive",
  getParentRoute: () => AdminRoute,
} as any)
const ProblemProblem_idIndexRoute = ProblemProblem_idIndexRouteImport.update({
  id: "/problem/$problem_id/",
  path: "/problem/$problem_id/",
  getParentRoute: () => rootRouteImport,
} as any)
const ProblemProblem_idResearchRoute =
  ProblemProblem_idResearchRouteImport.update({
    id: "/problem/$problem_id/research",
    path: "/problem/$problem_id/research",
    getParentRoute: () => rootRouteImport,
  } as any)
const ProblemProblem_idFilesRoute = ProblemProblem_idFilesRouteImport.update({
  id: "/problem/$problem_id/files",
  path: "/problem/$problem_id/files",
  getParentRoute: () => rootRouteImport,
} as any)
const ProblemProblem_idConversationsRoute =
  ProblemProblem_idConversationsRouteImport.update({
    id: "/problem/$problem_id/conversations",
    path: "/problem/$problem_id/conversations",
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminJobQueue_nameJob_idRoute =
  AdminJobQueue_nameJob_idRouteImport.update({
    id: "/job/$queue_name/$job_id",
    path: "/job/$queue_name/$job_id",
    getParentRoute: () => AdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute
  "/admin": typeof AdminRouteWithChildren
  "/create": typeof CreateRoute
  "/login": typeof LoginRoute
  "/settings": typeof SettingsRoute
  "/signup": typeof SignupRoute
  "/usage": typeof UsageRoute
  "/admin/archive": typeof AdminArchiveRoute
  "/admin/invites": typeof AdminInvitesRoute
  "/admin/jobs": typeof AdminJobsRoute
  "/admin/users": typeof AdminUsersRoute
  "/problem/$problem_id/conversations": typeof ProblemProblem_idConversationsRoute
  "/problem/$problem_id/files": typeof ProblemProblem_idFilesRoute
  "/problem/$problem_id/research": typeof ProblemProblem_idResearchRoute
  "/problem/$problem_id": typeof ProblemProblem_idIndexRoute
  "/admin/job/$queue_name/$job_id": typeof AdminJobQueue_nameJob_idRoute
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute
  "/admin": typeof AdminRouteWithChildren
  "/create": typeof CreateRoute
  "/login": typeof LoginRoute
  "/settings": typeof SettingsRoute
  "/signup": typeof SignupRoute
  "/usage": typeof UsageRoute
  "/admin/archive": typeof AdminArchiveRoute
  "/admin/invites": typeof AdminInvitesRoute
  "/admin/jobs": typeof AdminJobsRoute
  "/admin/users": typeof AdminUsersRoute
  "/problem/$problem_id/conversations": typeof ProblemProblem_idConversationsRoute
  "/problem/$problem_id/files": typeof ProblemProblem_idFilesRoute
  "/problem/$problem_id/research": typeof ProblemProblem_idResearchRoute
  "/problem/$problem_id": typeof ProblemProblem_idIndexRoute
  "/admin/job/$queue_name/$job_id": typeof AdminJobQueue_nameJob_idRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  "/": typeof IndexRoute
  "/admin": typeof AdminRouteWithChildren
  "/create": typeof CreateRoute
  "/login": typeof LoginRoute
  "/settings": typeof SettingsRoute
  "/signup": typeof SignupRoute
  "/usage": typeof UsageRoute
  "/admin/archive": typeof AdminArchiveRoute
  "/admin/invites": typeof AdminInvitesRoute
  "/admin/jobs": typeof AdminJobsRoute
  "/admin/users": typeof AdminUsersRoute
  "/problem/$problem_id/conversations": typeof ProblemProblem_idConversationsRoute
  "/problem/$problem_id/files": typeof ProblemProblem_idFilesRoute
  "/problem/$problem_id/research": typeof ProblemProblem_idResearchRoute
  "/problem/$problem_id/": typeof ProblemProblem_idIndexRoute
  "/admin/job/$queue_name/$job_id": typeof AdminJobQueue_nameJob_idRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | "/"
    | "/admin"
    | "/create"
    | "/login"
    | "/settings"
    | "/signup"
    | "/usage"
    | "/admin/archive"
    | "/admin/invites"
    | "/admin/jobs"
    | "/admin/users"
    | "/problem/$problem_id/conversations"
    | "/problem/$problem_id/files"
    | "/problem/$problem_id/research"
    | "/problem/$problem_id"
    | "/admin/job/$queue_name/$job_id"
  fileRoutesByTo: FileRoutesByTo
  to:
    | "/"
    | "/admin"
    | "/create"
    | "/login"
    | "/settings"
    | "/signup"
    | "/usage"
    | "/admin/archive"
    | "/admin/invites"
    | "/admin/jobs"
    | "/admin/users"
    | "/problem/$problem_id/conversations"
    | "/problem/$problem_id/files"
    | "/problem/$problem_id/research"
    | "/problem/$problem_id"
    | "/admin/job/$queue_name/$job_id"
  id:
    | "__root__"
    | "/"
    | "/admin"
    | "/create"
    | "/login"
    | "/settings"
    | "/signup"
    | "/usage"
    | "/admin/archive"
    | "/admin/invites"
    | "/admin/jobs"
    | "/admin/users"
    | "/problem/$problem_id/conversations"
    | "/problem/$problem_id/files"
    | "/problem/$problem_id/research"
    | "/problem/$problem_id/"
    | "/admin/job/$queue_name/$job_id"
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  CreateRoute: typeof CreateRoute
  LoginRoute: typeof LoginRoute
  SettingsRoute: typeof SettingsRoute
  SignupRoute: typeof SignupRoute
  UsageRoute: typeof UsageRoute
  ProblemProblem_idConversationsRoute: typeof ProblemProblem_idConversationsRoute
  ProblemProblem_idFilesRoute: typeof ProblemProblem_idFilesRoute
  ProblemProblem_idResearchRoute: typeof ProblemProblem_idResearchRoute
  ProblemProblem_idIndexRoute: typeof ProblemProblem_idIndexRoute
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/usage": {
      id: "/usage"
      path: "/usage"
      fullPath: "/usage"
      preLoaderRoute: typeof UsageRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/signup": {
      id: "/signup"
      path: "/signup"
      fullPath: "/signup"
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/settings": {
      id: "/settings"
      path: "/settings"
      fullPath: "/settings"
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/login": {
      id: "/login"
      path: "/login"
      fullPath: "/login"
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/create": {
      id: "/create"
      path: "/create"
      fullPath: "/create"
      preLoaderRoute: typeof CreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/admin": {
      id: "/admin"
      path: "/admin"
      fullPath: "/admin"
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/": {
      id: "/"
      path: "/"
      fullPath: "/"
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/admin/users": {
      id: "/admin/users"
      path: "/users"
      fullPath: "/admin/users"
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    "/admin/jobs": {
      id: "/admin/jobs"
      path: "/jobs"
      fullPath: "/admin/jobs"
      preLoaderRoute: typeof AdminJobsRouteImport
      parentRoute: typeof AdminRoute
    }
    "/admin/invites": {
      id: "/admin/invites"
      path: "/invites"
      fullPath: "/admin/invites"
      preLoaderRoute: typeof AdminInvitesRouteImport
      parentRoute: typeof AdminRoute
    }
    "/admin/archive": {
      id: "/admin/archive"
      path: "/archive"
      fullPath: "/admin/archive"
      preLoaderRoute: typeof AdminArchiveRouteImport
      parentRoute: typeof AdminRoute
    }
    "/problem/$problem_id/": {
      id: "/problem/$problem_id/"
      path: "/problem/$problem_id"
      fullPath: "/problem/$problem_id"
      preLoaderRoute: typeof ProblemProblem_idIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/problem/$problem_id/research": {
      id: "/problem/$problem_id/research"
      path: "/problem/$problem_id/research"
      fullPath: "/problem/$problem_id/research"
      preLoaderRoute: typeof ProblemProblem_idResearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/problem/$problem_id/files": {
      id: "/problem/$problem_id/files"
      path: "/problem/$problem_id/files"
      fullPath: "/problem/$problem_id/files"
      preLoaderRoute: typeof ProblemProblem_idFilesRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/problem/$problem_id/conversations": {
      id: "/problem/$problem_id/conversations"
      path: "/problem/$problem_id/conversations"
      fullPath: "/problem/$problem_id/conversations"
      preLoaderRoute: typeof ProblemProblem_idConversationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/admin/job/$queue_name/$job_id": {
      id: "/admin/job/$queue_name/$job_id"
      path: "/job/$queue_name/$job_id"
      fullPath: "/admin/job/$queue_name/$job_id"
      preLoaderRoute: typeof AdminJobQueue_nameJob_idRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminArchiveRoute: typeof AdminArchiveRoute
  AdminInvitesRoute: typeof AdminInvitesRoute
  AdminJobsRoute: typeof AdminJobsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminJobQueue_nameJob_idRoute: typeof AdminJobQueue_nameJob_idRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminArchiveRoute: AdminArchiveRoute,
  AdminInvitesRoute: AdminInvitesRoute,
  AdminJobsRoute: AdminJobsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminJobQueue_nameJob_idRoute: AdminJobQueue_nameJob_idRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  CreateRoute: CreateRoute,
  LoginRoute: LoginRoute,
  SettingsRoute: SettingsRoute,
  SignupRoute: SignupRoute,
  UsageRoute: UsageRoute,
  ProblemProblem_idConversationsRoute: ProblemProblem_idConversationsRoute,
  ProblemProblem_idFilesRoute: ProblemProblem_idFilesRoute,
  ProblemProblem_idResearchRoute: ProblemProblem_idResearchRoute,
  ProblemProblem_idIndexRoute: ProblemProblem_idIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
