/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root"
import { Route as LoginRouteImport } from "./routes/login"
import { Route as CreateRouteImport } from "./routes/create"
import { Route as ArchiveRouteImport } from "./routes/archive"
import { Route as IndexRouteImport } from "./routes/index"
import { Route as ProblemProblem_idRouteImport } from "./routes/problem/$problem_id"

const LoginRoute = LoginRouteImport.update({
  id: "/login",
  path: "/login",
  getParentRoute: () => rootRouteImport,
} as any)
const CreateRoute = CreateRouteImport.update({
  id: "/create",
  path: "/create",
  getParentRoute: () => rootRouteImport,
} as any)
const ArchiveRoute = ArchiveRouteImport.update({
  id: "/archive",
  path: "/archive",
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any)
const ProblemProblem_idRoute = ProblemProblem_idRouteImport.update({
  id: "/problem/$problem_id",
  path: "/problem/$problem_id",
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute
  "/archive": typeof ArchiveRoute
  "/create": typeof CreateRoute
  "/login": typeof LoginRoute
  "/problem/$problem_id": typeof ProblemProblem_idRoute
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute
  "/archive": typeof ArchiveRoute
  "/create": typeof CreateRoute
  "/login": typeof LoginRoute
  "/problem/$problem_id": typeof ProblemProblem_idRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  "/": typeof IndexRoute
  "/archive": typeof ArchiveRoute
  "/create": typeof CreateRoute
  "/login": typeof LoginRoute
  "/problem/$problem_id": typeof ProblemProblem_idRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: "/" | "/archive" | "/create" | "/login" | "/problem/$problem_id"
  fileRoutesByTo: FileRoutesByTo
  to: "/" | "/archive" | "/create" | "/login" | "/problem/$problem_id"
  id:
    | "__root__"
    | "/"
    | "/archive"
    | "/create"
    | "/login"
    | "/problem/$problem_id"
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArchiveRoute: typeof ArchiveRoute
  CreateRoute: typeof CreateRoute
  LoginRoute: typeof LoginRoute
  ProblemProblem_idRoute: typeof ProblemProblem_idRoute
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/login": {
      id: "/login"
      path: "/login"
      fullPath: "/login"
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/create": {
      id: "/create"
      path: "/create"
      fullPath: "/create"
      preLoaderRoute: typeof CreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/archive": {
      id: "/archive"
      path: "/archive"
      fullPath: "/archive"
      preLoaderRoute: typeof ArchiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/": {
      id: "/"
      path: "/"
      fullPath: "/"
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/problem/$problem_id": {
      id: "/problem/$problem_id"
      path: "/problem/$problem_id"
      fullPath: "/problem/$problem_id"
      preLoaderRoute: typeof ProblemProblem_idRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArchiveRoute: ArchiveRoute,
  CreateRoute: CreateRoute,
  LoginRoute: LoginRoute,
  ProblemProblem_idRoute: ProblemProblem_idRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
