/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root"
import { Route as UsageRouteImport } from "./routes/usage"
import { Route as LoginRouteImport } from "./routes/login"
import { Route as CreateRouteImport } from "./routes/create"
import { Route as ArchiveRouteImport } from "./routes/archive"
import { Route as IndexRouteImport } from "./routes/index"
import { Route as ProblemProblem_idIndexRouteImport } from "./routes/problem/$problem_id/index"
import { Route as ProblemProblem_idResearchRouteImport } from "./routes/problem/$problem_id/research"
import { Route as ProblemProblem_idFilesRouteImport } from "./routes/problem/$problem_id/files"
import { Route as ProblemProblem_idConversationsRouteImport } from "./routes/problem/$problem_id/conversations"

const UsageRoute = UsageRouteImport.update({
  id: "/usage",
  path: "/usage",
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: "/login",
  path: "/login",
  getParentRoute: () => rootRouteImport,
} as any)
const CreateRoute = CreateRouteImport.update({
  id: "/create",
  path: "/create",
  getParentRoute: () => rootRouteImport,
} as any)
const ArchiveRoute = ArchiveRouteImport.update({
  id: "/archive",
  path: "/archive",
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any)
const ProblemProblem_idIndexRoute = ProblemProblem_idIndexRouteImport.update({
  id: "/problem/$problem_id/",
  path: "/problem/$problem_id/",
  getParentRoute: () => rootRouteImport,
} as any)
const ProblemProblem_idResearchRoute =
  ProblemProblem_idResearchRouteImport.update({
    id: "/problem/$problem_id/research",
    path: "/problem/$problem_id/research",
    getParentRoute: () => rootRouteImport,
  } as any)
const ProblemProblem_idFilesRoute = ProblemProblem_idFilesRouteImport.update({
  id: "/problem/$problem_id/files",
  path: "/problem/$problem_id/files",
  getParentRoute: () => rootRouteImport,
} as any)
const ProblemProblem_idConversationsRoute =
  ProblemProblem_idConversationsRouteImport.update({
    id: "/problem/$problem_id/conversations",
    path: "/problem/$problem_id/conversations",
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute
  "/archive": typeof ArchiveRoute
  "/create": typeof CreateRoute
  "/login": typeof LoginRoute
  "/usage": typeof UsageRoute
  "/problem/$problem_id/conversations": typeof ProblemProblem_idConversationsRoute
  "/problem/$problem_id/files": typeof ProblemProblem_idFilesRoute
  "/problem/$problem_id/research": typeof ProblemProblem_idResearchRoute
  "/problem/$problem_id": typeof ProblemProblem_idIndexRoute
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute
  "/archive": typeof ArchiveRoute
  "/create": typeof CreateRoute
  "/login": typeof LoginRoute
  "/usage": typeof UsageRoute
  "/problem/$problem_id/conversations": typeof ProblemProblem_idConversationsRoute
  "/problem/$problem_id/files": typeof ProblemProblem_idFilesRoute
  "/problem/$problem_id/research": typeof ProblemProblem_idResearchRoute
  "/problem/$problem_id": typeof ProblemProblem_idIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  "/": typeof IndexRoute
  "/archive": typeof ArchiveRoute
  "/create": typeof CreateRoute
  "/login": typeof LoginRoute
  "/usage": typeof UsageRoute
  "/problem/$problem_id/conversations": typeof ProblemProblem_idConversationsRoute
  "/problem/$problem_id/files": typeof ProblemProblem_idFilesRoute
  "/problem/$problem_id/research": typeof ProblemProblem_idResearchRoute
  "/problem/$problem_id/": typeof ProblemProblem_idIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | "/"
    | "/archive"
    | "/create"
    | "/login"
    | "/usage"
    | "/problem/$problem_id/conversations"
    | "/problem/$problem_id/files"
    | "/problem/$problem_id/research"
    | "/problem/$problem_id"
  fileRoutesByTo: FileRoutesByTo
  to:
    | "/"
    | "/archive"
    | "/create"
    | "/login"
    | "/usage"
    | "/problem/$problem_id/conversations"
    | "/problem/$problem_id/files"
    | "/problem/$problem_id/research"
    | "/problem/$problem_id"
  id:
    | "__root__"
    | "/"
    | "/archive"
    | "/create"
    | "/login"
    | "/usage"
    | "/problem/$problem_id/conversations"
    | "/problem/$problem_id/files"
    | "/problem/$problem_id/research"
    | "/problem/$problem_id/"
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArchiveRoute: typeof ArchiveRoute
  CreateRoute: typeof CreateRoute
  LoginRoute: typeof LoginRoute
  UsageRoute: typeof UsageRoute
  ProblemProblem_idConversationsRoute: typeof ProblemProblem_idConversationsRoute
  ProblemProblem_idFilesRoute: typeof ProblemProblem_idFilesRoute
  ProblemProblem_idResearchRoute: typeof ProblemProblem_idResearchRoute
  ProblemProblem_idIndexRoute: typeof ProblemProblem_idIndexRoute
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/usage": {
      id: "/usage"
      path: "/usage"
      fullPath: "/usage"
      preLoaderRoute: typeof UsageRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/login": {
      id: "/login"
      path: "/login"
      fullPath: "/login"
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/create": {
      id: "/create"
      path: "/create"
      fullPath: "/create"
      preLoaderRoute: typeof CreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/archive": {
      id: "/archive"
      path: "/archive"
      fullPath: "/archive"
      preLoaderRoute: typeof ArchiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/": {
      id: "/"
      path: "/"
      fullPath: "/"
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/problem/$problem_id/": {
      id: "/problem/$problem_id/"
      path: "/problem/$problem_id"
      fullPath: "/problem/$problem_id"
      preLoaderRoute: typeof ProblemProblem_idIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/problem/$problem_id/research": {
      id: "/problem/$problem_id/research"
      path: "/problem/$problem_id/research"
      fullPath: "/problem/$problem_id/research"
      preLoaderRoute: typeof ProblemProblem_idResearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/problem/$problem_id/files": {
      id: "/problem/$problem_id/files"
      path: "/problem/$problem_id/files"
      fullPath: "/problem/$problem_id/files"
      preLoaderRoute: typeof ProblemProblem_idFilesRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/problem/$problem_id/conversations": {
      id: "/problem/$problem_id/conversations"
      path: "/problem/$problem_id/conversations"
      fullPath: "/problem/$problem_id/conversations"
      preLoaderRoute: typeof ProblemProblem_idConversationsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArchiveRoute: ArchiveRoute,
  CreateRoute: CreateRoute,
  LoginRoute: LoginRoute,
  UsageRoute: UsageRoute,
  ProblemProblem_idConversationsRoute: ProblemProblem_idConversationsRoute,
  ProblemProblem_idFilesRoute: ProblemProblem_idFilesRoute,
  ProblemProblem_idResearchRoute: ProblemProblem_idResearchRoute,
  ProblemProblem_idIndexRoute: ProblemProblem_idIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
